//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public class AnimalKingdom
{
    private Herbivore _herbivore;

    private Carnivore _carnivore;

    public AnimalKingdom(ContinentFactory factory)
    {
        _carnivore = factory.CreateCarnivore();
        _herbivore = factory.CreateHerbivore();
    }

	public virtual void RunFoodChain()
	{
        _carnivore.Eat(_herbivore);
	}

}

