//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public class Herbivore
{
	public virtual void Eat()
	{
		throw new System.NotImplementedException();
	}

}

