//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class Wolf : Carnivore
{
    public override void Eat(Herbivore h)
    {
        //Eat bison
        Console.WriteLine(this.GetType().Name + " eats " + h.GetType().Name);
    }
}

